### PR TITLE
Add @kjetil's tester

### PR DESCRIPTION
**Pull request by michielbdejong**
WiP (blocked on https://github.com/kjetilk/p5-web-solid-test-basic/issues/1 currently)

### CODE REVIEW

**Comment by michielbdejong** [comment]
oh now this became a PR on my fork... will clean that up tomorrow.

**Comment by michielbdejong** [comment]
we should also change this so that it tests http://server:8080/ and not https://kjetiltest4.dev.inrupt.net/

**Comment by kjetilk** [comment]
Ah, right, you need to take the Dockerfile from https://github.com/kjetilk/p5-web-solid-test-basic/blob/4304edc4b59383c46a90f91fcadb738e64b777ca/Dockerfile I don't know where that should best live?

**Comment by kjetilk** [comment]
Actually, I'd like to have the test subject parameterized somehow. It should have a different default, but my goal is that you can just give it a URL and it will test that server.

**Comment by michielbdejong** [comment]
ok, will use the updated one. This repo runs testers against servers in a local testnet, so the server under test is always http://server:8080 there.

**Pull request merged**
